cask_args appdir: "/Applications"
tap "osgeo/osgeo4mac"
brew "postgresql"
brew "postgis"
brew "geoserver"
brew "spatialite-tools"
brew "spatialite-gui"
cask "josm"
cask "db-browser-for-sqlite"
cask "sqlitestudio"
cask "dbeaver-community"
